#!/usr/bin/env bash
# This script configures localhost to resolve to 127.0.0.2 and facebook.com to 8.8.8.8
sed -i 's/127.0.0.1\(.*\)localhost/127.0.0.2\1localhost/' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
